apiVersion: v1
kind: Service
metadata:
  name: wordpress-web-service
  labels:
    app: wordpress-web
spec:
  type: NodePort
  ports:
    - port: 30030
      protocol: TCP
      nodePort: 30030
      targetPort: wordpress-web
  selector:
    app: wordpress-web