apiVersion: v1
kind: Service
metadata:
  name: wordpress-db-service
  labels:
    app: wordpress-my-sql
spec:
  type: NodePort
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: wordpress-my-sql